export enum ContactText {
  SECTION_TITLE = "Get In Touch",
  SECTION_DESCRIPTION = "Have questions or ready to streamline your logistics? Our team at Houston Logistics is here to help.",
  CONVERSATION_TITLE = "Let's Start a Conversation",
  CONVERSATION_DESCRIPTION = "Don't wait to simplify your logistics. Reach out now and start a partnership built on speed, reliability, and efficiency.",
  EMAIL_LABEL = "Email Us",
  EMAIL_VALUE = "partnerships@logistics.com",
  OFFICE_LABEL = "Visit Our Office",
  OFFICE_VALUE = "123 Business District, City",
  BENEFITS_TITLE = "Partnership Benefits",
  FORM_NAME_LABEL = "Full Name *",
  FORM_NAME_PLACEHOLDER = "Enter your full name",
  FORM_JOB_LABEL = "Job Title *",
  FORM_JOB_PLACEHOLDER = "Enter your job title",
  FORM_EMAIL_LABEL = "Email Address *",
  FORM_EMAIL_PLACEHOLDER = "Enter your email address",
  FORM_COMPANY_LABEL = "Company Name *",
  FORM_COMPANY_PLACEHOLDER = "Enter your company name",
  FORM_MESSAGE_LABEL = "Message *",
  FORM_MESSAGE_PLACEHOLDER = "Tell us about your partnership interests and goals...",
  FORM_SUBMIT_BUTTON = "Send Message",
  FORM_SUBMITTING = "Sending...",
  SUCCESS_TOAST_TITLE = "Message Sent Successfully!",
  SUCCESS_TOAST_DESCRIPTION = "We'll get back to you within 24 hours.",
}
